app/tratamento/forms.py
# -*- encoding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField

class SearchInformacaoTratamentoForm(FlaskForm):

    choices = [('', 'Selecione'), ('Doença de Crohn', 'Doença de Crohn'), ('Colite Ulcerativa', 'Colite Ulcerativa')]

    protocolo = SelectField('Protocolo', choices=choices)
    medicamento = StringField('Medicamento')

    submit = SubmitField('Buscar')

app/tratamento/__init__.py
from flask import Blueprint

blueprint = Blueprint('tratamento_blueprint', __name__, template_folder='templates', url_prefix='/tratamento')

app/tratamento/routes.py
# -*- encoding: utf-8 -*-

from flask import render_template, request, redirect, url_for
from flask_login import login_required
from app.tratamento import blueprint
from app import db
from app.base.models import InformacaoTratamento, Unaccent, Search
from app.tratamento.forms import SearchInformacaoTratamentoForm


@blueprint.route('/listar', methods=['GET', 'POST'])
@login_required
def listar_tratamentos():
    pagina = request.args.get('pagina', default=1, type=int)
    protocolo = request.args.get('protocolo', None, type=str)
    medicamento = request.args.get('medicamento', None, type=str)

    search_form = SearchInformacaoTratamentoForm()
    if search_form.validate_on_submit():
        return redirect(url_for('tratamento_blueprint.listar_tratamentos',
                                pagina=1,
                                protocolo=search_form.protocolo.data,
                                medicamento=search_form.medicamento.data))
    elif request.method == 'GET':
        search_form.protocolo.data = protocolo
        search_form.medicamento.data = medicamento

    qtd_pagina = 8
    query_string = []
    if protocolo:
        query_string.append(InformacaoTratamento.protocolo == protocolo)
    if medicamento:
        str_unnacented = Search.removeAccent(medicamento)
        query_string.append(Unaccent(InformacaoTratamento.medicamento).ilike("%{}%".format(str_unnacented)))
    query = db.session.query(InformacaoTratamento).filter(db.and_(*query_string))

    tratamentos = query.paginate(pagina, qtd_pagina, error_out=False)

    return render_template('tratamentos.html',  title='Tratamentos', tratamentos=tratamentos,
                           search_form=search_form)

@blueprint.route('/detalhes/<int:id_tratamento>', methods=['GET', 'POST'])
@login_required
def detalhar_tratamento(id_tratamento):
    tratamento = InformacaoTratamento.query.filter_by(id=id_tratamento).first()
    return render_template('tratamento_detalhe.html', title='Tratamento detalhe', tratamento=tratamento)

app/tratamento/templates/tratamento_detalhe.html
{% extends "base-site.html" %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<style>
label.thick {
  font-weight: bold;
}
.card-header.thick {
  font-weight: bold;
}
</style>

<div class="container-fluid">
    <div class="fade-in">
        <div class="card">
            <div class="card-header"><strong>{{ tratamento.medicamento|safe }} {{ tratamento.concentracao|safe }} {{ tratamento.forma_farmaceutica|safe }}</strong></div>
            <div class="card-body">
                <label class="thick">Patologia</label>
                <p>{{ tratamento.protocolo|safe }}</p>
                <label class="thick">Forma de administração</label>
                <p>{{ tratamento.forma_administracao|safe }}</p>
                <label class="thick">Principais RAMs</label>
                <p>{{ tratamento.principais_rams|safe }}</p>
                <label class="thick">Cuidados especiais</label>
                <p>{{ tratamento.cuidados_especiais|safe }}</p>
                <label class="thick">Armazenamento e transporte</label>
                <p>{{ tratamento.armazenamento_transporte|safe }}</p>
                <div class="card text-white bg-success">
                  <div class="card-header"><strong>Informações ao farmacêutico/acadêmico</strong></div>
                  <div class="card-body">
                    <label class="thick">Dose usual</label>
                    <p>{{ tratamento.dose_usual|safe }}</p>
                    <label class="thick">Associações na literatura</label>
                    <p>{{ tratamento.associacoes_literatura|safe }}</p>
                    <label class="thick">Indicações de mecanismo</label>
                    <p>{{ tratamento.indicacoes_mecanismo|safe }}</p>
                    <label class="thick">Interações graves</label>
                    <p>{{ tratamento.interacoes_graves|safe }}</p>
                    <label class="thick">Interações do medicamento com doenças</label>
                    <p>{{ tratamento.relacao_medicamento_doenca|safe }}</p>
                    <label class="thick">Interações medicamento/alimento</label>
                    <p>{{ tratamento.interacoes_medicamento_alimento|safe }}</p>
                    <label class="thick">Ajuste de dose</label>
                    <p>{{ tratamento.ajuste_dose|safe }}</p>
                    <label class="thick">Risco na gravidez</label>
                    <p>{{ tratamento.risco_gravidez|safe }}</p>
                  </div>
                </div>
                <label class="thick">Referências</label>
                <p>{{ tratamento.referencia|safe }}</p>
            </div>
        </div>
    </div>



</div>

{% endblock content %}

app/tratamento/templates/tratamentos.html
{% extends "base-site.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="fade-in">

        <div class="card">
            <div class="card-header">
                <strong>Busca</strong>
            </div>
             <div class="card-body">
                 <form method="post">
                     {{ search_form.hidden_tag() }}
                 <div class="row">
                     <div class="col-sm-2 form-group">
                         {{ search_form.protocolo.label() }}
                         {{ search_form.protocolo(class="form-control") }}
                     </div>
                     <div class="col-sm-4 form-group">
                        {{ search_form.medicamento.label() }}
                        {{ search_form.medicamento(class="form-control") }}
                     </div>
                        <div class="col-sm-6 form-group align-self-end">
                          {{ search_form.submit(class="btn btn-success") }}
                        </div>
                 </div>
                 </form>
             </div>
        </div>

          <div class="card">
            <div class="card-header"><strong>Tratamentos</strong>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-responsive-sm table-striped">
                        <thead>
                          <tr>
                            <th>Protocolo</th>
                            <th>Medicamento</th>
                            <th>Concentração</th>
                            <th>Forma farmacêutica</th>
                            <th>Ações</th>
                          </tr>
                        </thead>
                        <tbody>
                         <tr>
                            {% for tratamento in tratamentos.items %}
                            <td>{{ tratamento.protocolo }}</td>
                            <td>{{ tratamento.medicamento }}</td>
                            <td>{{ tratamento.concentracao }}</td>
                            <td>{{ tratamento.forma_farmaceutica }}</td>
                             <td>
                                <button class="btn btn-info" type="button" onclick="location.href='{{ url_for('tratamento_blueprint.detalhar_tratamento', id_tratamento=tratamento.id) }}'">
                                    <svg class="c-icon">
                                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-magnifying-glass"></use>
                                    </svg> Mais detalhes
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                      {{ pagination(tratamentos, 'tratamento_blueprint.listar_tratamentos', tratamentos.prev_num, tratamentos.next_num) }}
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}