app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, StringField, SubmitField, BooleanField
from wtforms.validators import InputRequired, Email, DataRequired, ValidationError, EqualTo
from app.base.models import User



class CreateAccountForm(FlaskForm):
    username = StringField('Username'     , id='username_create' , validators=[DataRequired()])
    name = StringField('Nome'     , id='name_create' , validators=[DataRequired()])
    email    = StringField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    #password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])
    submit = SubmitField('Salvar')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Esse email já está cadastrado. Informe outro.')

    def validate_username(self, username):
        user = User.query.filter_by(email=username.data).first()
        if user is not None:
            raise ValidationError('Esse usuário já está cadastrado. Tente outro.')

class EditAccountForm(FlaskForm):
    #funcao para editar
    def __init__(self, original_email, *args, **kwargs):
        super(EditAccountForm, self).__init__(*args, **kwargs)
        self.original_email = original_email

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).all()
        if len(user) > 1:
            raise ValidationError('Esse email já está cadastrado. Informe outro.')

    username = StringField('Username', id='username_create', validators=[DataRequired()], render_kw={'readonly': True})
    name = StringField('Nome', id='name_create', validators=[DataRequired()])
    email = StringField('Email', id='email_create', validators=[DataRequired(), Email()])
    active = BooleanField('Ativo')
    submit = SubmitField('Salvar')

# reset and forget password
class ResetPasswordRequestForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email(message="Email inválido.")])
    submit = SubmitField('Enviar link')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('Email não encontrado.')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Senha', validators=[DataRequired()])
    password2 = PasswordField('Confirmar senha', validators=[DataRequired(), EqualTo('password', message="A senha deve ser igual.")])
    submit = SubmitField('Resetar')

app/admin/__init__.py
from flask import Blueprint

blueprint = Blueprint('admin_blueprint', __name__, template_folder='templates', url_prefix='/admin')

app/admin/routes.py
from flask import redirect, url_for, render_template, flash, request, jsonify
from app.admin import blueprint
from app import db
from flask_login import current_user
from app.base.models import User, Unaccent, Search
from flask_login import login_required
from app.admin.forms import CreateAccountForm, EditAccountForm
from app.base.forms import SearchPessoaForm
import random
import datetime


@blueprint.route('/users/listar', methods=['GET', 'POST'])
@login_required
def users():
    pagina = request.args.get('pagina', default=1, type=int)
    username = request.args.get('username', None, type=str)
    nome = request.args.get('nome', None, type=str)
    email = request.args.get('email', None, type=str)

    search_form = SearchPessoaForm()
    if search_form.validate_on_submit():
        return redirect(url_for('admin_blueprint.users', pagina=1,
                                username=search_form.username.data,
                                nome=search_form.nome.data,
                                email=search_form.email.data,
                                ))
    elif request.method == 'GET':
        search_form.username.data = username
        search_form.nome.data = nome
        search_form.email.data = email

    qtd_pagina = 10
    query_string = []
    if username:
        str_unnacented = Search.removeAccent(username)
        query_string.append(Unaccent(User.username).ilike("%{}%".format(str_unnacented)))
    if nome:
        str_unnacented = Search.removeAccent(nome)
        query_string.append(Unaccent(User.name).ilike("%{}%".format(str_unnacented)))
    if email:
        str_unnacented = Search.removeAccent(email)
        query_string.append(Unaccent(User.email).ilike("%{}%".format(str_unnacented)))

    query = db.session.query(User).filter(db.and_(*query_string))

    if current_user.is_authenticated and current_user.admin:
        form = CreateAccountForm()
        users = query.order_by("username").paginate(pagina, qtd_pagina, error_out=False)

        return render_template('users.html', title='Usuários', users=users, form=form, search_form=search_form)
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    form = CreateAccountForm()
    if form.validate_on_submit():
        user = User(
         username=form.username.data,
         name=form.name.data,
         email=form.email.data,
         active=True,
         password=str(random.randint(1, 99999))
        )
        db.session.add(user)
        db.session.commit()
        flash('Usuário adicionado com sucesso')
        return jsonify(status='ok')
    return render_template('add_user.html', methods=['GET', 'POST'], form=form)

@blueprint.route('/edit_user/<id>', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    user = User.query.filter_by(id=id).first()
    form = EditAccountForm(user.email)
    if form.validate_on_submit():
        user.name = form.name.data
        user.email = form.email.data
        user.active = form.active.data
        user.updated_in = datetime.datetime.utcnow()
        db.session.commit()
        flash('Usuário editado com sucesso')
        return jsonify(status='ok')
    elif request.method == 'GET':
        form.username.data = user.username
        form.name.data = user.name
        form.email.data = user.email
        form.active.data = user.active
    return render_template('edit_user.html', methods=['GET', 'POST'], form=form)

app/admin/templates/add_user.html
{% from "macros/base_macro.html" import error_form %}

<form role="form" method="post" id="addUserForm">
    <div class="modal-header">
        <h4 class="modal-title">Adicionar usuário</h4>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
    <div class="modal-body">
        {{ error_form(form) }}
        {{ form.hidden_tag() }}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <svg class="c-icon"><use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-voice-over-record"></use></svg>
                </span>
            </div>
            {{ form.username(placeholder="Nome de usuário (por exemplo: joao.pedro)", class="form-control") }}
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <span class="input-group-text">
                <svg class="c-icon"><use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use></svg>
              </span></div>
          {{ form.name(placeholder="Nome", class="form-control") }}
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <span class="input-group-text">
                <svg class="c-icon"><use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-closed"></use></svg>
              </span></div>
          {{ form.email(placeholder="Email", class="form-control") }}
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
        {{ form.submit(class="btn btn-success") }}
    </div>
</form>

app/admin/templates/alert_base.html
{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in messages %}
    <div id="inner-message" class="alert alert-info" role="alert" style="width: 100%;">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
    {% endfor %}
{% endif %}
{% endwith %}

app/admin/templates/edit_user.html
<form role="form" method="post" id="editUserForm">
    {{ form.hidden_tag() }}
    <div class="modal-header">
        <h4 class="modal-title">Editar usuário</h4>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
    <div class="modal-body">
        <div>
            {% if form.errors %}
                <ul class="errors">
                    {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                        {% for error in field_errors %}
                            <li>[{{ form[field_name].label }}] {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <svg class="c-icon"><use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-voice-over-record"></use></svg>
                </span>
            </div>
            {{ form.username(placeholder="Nome de usuário (por exemplo: joao.pedro)", class="form-control") }}
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <span class="input-group-text">
                <svg class="c-icon"><use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use></svg>
              </span></div>
          {{ form.name(placeholder="Nome", class="form-control") }}
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <span class="input-group-text">
                <svg class="c-icon"><use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-closed"></use></svg>
              </span></div>
          {{ form.email(placeholder="Email", class="form-control") }}
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <div class="row">
                    <div class="col-sm-6">
                        <label class="c-switch c-switch-label c-switch-success">
                            {{ form.active(class="c-switch-input", type="checkbox", onclick="toggleActiveLabel()") }}
                            <span class="c-switch-slider"></span>
                        </label>
                    </div>
                    <div class="col-sm-6">
                        <label id="activeLabelText">
                        {% if form.active.data %}
                        Ativo
                        {% else %}
                        Inativo
                        {% endif %}
                        </label>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
        {{ form.submit(class="btn btn-success") }}
    </div>
</form>

app/admin/templates/user.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Edit Profile</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/admin/templates/users.html
{% extends "base-site.html" %}
{% block title %} Usuários {% endblock %}

{% block content %}

<script>
$(document).ready(function(){
  $("#addUserButton").click(function(){
    var url = "{{ url_for('admin_blueprint.add_user') }}"
    $.get(url, function(data, status){
      $('#addUserModal .modal-content').html(data);
      $('#addUserModal').modal();

      $('body').on('submit','#addUserForm', function() {
      event.preventDefault();
      $.post(url, data=$('#addUserForm').serialize(), function(data) {
        if (data.status == 'ok') {
          $('#addUserModal').modal('hide');
          location.reload();
        }
        else {
          $('#addUserModal .modal-content').html(data);
        }
      });
    })
    });
  });

    $("button[name='editUserButton']").click(function(){
        var idUser = $(this).attr("id").split('-')[1];
        var url = Flask.url_for('admin_blueprint.edit_user', {"id": idUser});
        $.get(url, function(data, status){
          $('#editUserModal .modal-content').html(data);
          $('#editUserModal').modal();

          $('body').on('submit','#editUserForm', function() {
          event.preventDefault();
          $.post(url, data=$('#editUserForm').serialize(), function(data) {
            if (data.status == 'ok') {
              $('#editUserModal').modal('hide');
              location.reload();
            }
            else {
              $('#editUserModal .modal-content').html(data);
            }
          });
        })
        });
    });

});


function toggleActiveLabel(){
    var txt = $("#activeLabelText").text().trim();
    if(txt == 'Ativo')
        $("#activeLabelText").text('Inativo');
    else
        $("#activeLabelText").text('Ativo');
}
</script>

    <div class="container-fluid">
        <div class="fade-in">

        <div class="card">
            <div class="card-header">
                <strong>Busca</strong>
            </div>
             <div class="card-body">
                 <form method="post">
                     {{ search_form.hidden_tag() }}
                 <div class="row">
                     <div class="col-sm-3 form-group">
                         {{ search_form.username.label() }}
                         {{ search_form.username(class="form-control") }}
                     </div>
                     <div class="col-sm-3 form-group">
                            {{ search_form.nome.label() }}
                            {{ search_form.nome(class="form-control") }}
                     </div>
                     <div class="col-sm-3 form-group">
                            {{ search_form.email.label() }}
                            {{ search_form.email(class="form-control") }}
                     </div>
                        <div class="col-sm-3 form-group align-self-end">
                          {{ search_form.submit(class="btn btn-success") }}
                        </div>
                 </div>
                 </form>
             </div>
        </div>

          <div class="card">
            <div class="card-header"> Usuários
                <div class="card-header-actions">
                  <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#addUserModal" id="addUserButton">
                    <svg class="c-icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user-follow"></use>
                    </svg> Adicionar
                  </button>
                </div>

            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-responsive-sm table-striped">
                        <thead>
                          <tr>
                            <th>Username</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                         <tr>
                            {% for user in users.items %}
                            <td>{{ user.username }}</td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.email }}</td>
                            {% if user.active %}
                            <td><span class="badge badge-success">Ativo</span></td>
                            {% else %}
                            <td><span class="badge badge-secondary">Inativo</span></td>
                            {% endif %}
                            <td>
                                <button class="btn btn-warning" type="button" data-toggle="modal" data-target="#editUserModal" name="editUserButton" id="editButton-{{ user.id }}">
                                    <svg class="c-icon">
                                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
                                    </svg> Editar
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                      {{ pagination(users, 'admin_blueprint.users', users.prev_num, users.next_num) }}
                    </div>
                </div>
            </div>
          </div>

        </div>

        <!-- addUser modal-->
        <div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-keyboard="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                </div>
            </div>
        </div>

        <!-- editUser modal-->
        <div class="modal fade" id="editUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-keyboard="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                </div>
            </div>
        </div>
    </div>

{% endblock content %}