app/paciente/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length, NoneOf
from app.base.models import Paciente


class PacienteForm(FlaskForm):
    cpf = StringField('CPF', validators=[DataRequired(), Length(min=11, max=11, message='Digite o CPF apenas com números e 11 caracteres')], render_kw={'autocomplete': 'off'})
    nome = StringField('Nome', validators=[DataRequired(), Length(min=-1, max=200, message='Digite um nome menor.')], render_kw={'autocomplete': 'off'})
    data_nascimento = DateField('Data de nascimento', format='%d/%m/%Y', validators=[DataRequired('Preencha com uma data.')], render_kw={'autocomplete': 'off'})
    sexo = SelectField('Sexo', choices=[('selecione', 'Selecione...'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')],
                       validators=[NoneOf('selecione', message="Escolha uma opção válida")], render_kw={'autocomplete': 'off'})
    telefone = StringField('Telefone', validators=[Length(min=-1, max=20, message='Digite um telefone menor.')], render_kw={'autocomplete': 'off'})
    email = StringField('Email', validators=[Length(min=-1, max=500, message='Digite um email menor.')], render_kw={'autocomplete': 'off'})
    cep = StringField('CEP', validators=[Length(min=-1, max=8, message='Digite apenas os números.')], render_kw={'autocomplete': 'off'})
    endereco = StringField('Endereço', validators=[Length(min=-1, max=500, message='Digite um endereço menor.')], render_kw={'autocomplete': 'off'})
    complemento = StringField('Complemento', validators=[Length(min=-1, max=500, message='Digite um complemento menor.')], render_kw={'autocomplete': 'off'})
    referencia = StringField('Ponto de referência', validators=[Length(min=-1, max=500, message='Digite uma referência menor.')], render_kw={'autocomplete': 'off'})
    submit = SubmitField('Salvar')

    def validate_cpf(self, cpf):
        paciente = Paciente.query.filter_by(cpf=cpf.data).first()
        if paciente is not None:
            raise ValidationError('Esse CPF já existe na base. Cadastre outro.')

class EditPacienteForm(PacienteForm):
    cpf = StringField('CPF', render_kw={'readonly': True})

    def validate_cpf(self, cpf):
        pass

    def __init__(self, original_cpf, *args, **kwargs):
        super(EditPacienteForm, self).__init__(*args, **kwargs)
        self.original_cpf = original_cpf

app/paciente/__init__.py
from flask import Blueprint

blueprint = Blueprint('paciente_blueprint', __name__, template_folder='templates', url_prefix='/paciente')

app/paciente/routes.py
# -*- encoding: utf-8 -*-

from flask import render_template, redirect, request, url_for, flash
from flask_login import current_user, login_required
import datetime
from app import db
from app.paciente import blueprint
from app.paciente.forms import PacienteForm, EditPacienteForm
from app.base.forms import SearchPessoaForm
from app.base.models import Paciente, Unaccent, Search


@blueprint.route('/listar', methods=['GET', 'POST'])
@login_required
def pacientes():
    pagina = request.args.get('pagina', default=1, type=int)
    cpf = request.args.get('cpf', None, type=str)
    nome = request.args.get('nome', None, type=str)

    search_form = SearchPessoaForm()
    if search_form.validate_on_submit():
        return redirect(url_for('paciente_blueprint.pacientes', pagina=1, cpf=search_form.cpf.data, nome=search_form.nome.data))
    elif request.method == 'GET':
        search_form.cpf.data = cpf
        search_form.nome.data = nome

    qtd_pagina = 10
    query_string = []
    if cpf:
        query_string.append(Paciente.cpf == cpf)
    if nome:
        str_unnacented = Search.removeAccent(nome)
        query_string.append(Unaccent(Paciente.nome).ilike("%{}%".format(str_unnacented)))
    query = db.session.query(Paciente).filter(db.and_(*query_string))

    pacientes = query.order_by("nome").paginate(pagina, qtd_pagina, error_out=False)

    return render_template('pacientes.html', title='Pacientes', pacientes=pacientes, search_form=search_form)

@blueprint.route('/adicionar', methods=['GET', 'POST'])
@login_required
def adicionar_paciente():
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))

    form = PacienteForm()
    if form.validate_on_submit():
        paciente = Paciente(
             cpf=form.cpf.data,
             nome=form.nome.data,
             data_nascimento=form.data_nascimento.data,
             sexo=form.sexo.data,
             telefone=form.telefone.data,
             email=form.email.data,
             cep=form.cep.data,
             endereco=form.endereco.data,
             complemento=form.complemento.data,
             referencia=form.referencia.data,
             user=current_user
        )
        db.session.add(paciente)
        db.session.commit()
        flash('Usuário adicionado com sucesso')
        return redirect(url_for('paciente_blueprint.pacientes', pagina=1))
    return render_template('paciente.html', methods=['GET', 'POST'], form=form, titulo_card="Adicionar paciente")

@blueprint.route('/editar/<id>', methods=['GET', 'POST'])
@login_required
def edit_paciente(id):
    paciente = Paciente.query.filter_by(id=id).first()
    form = EditPacienteForm(paciente.cpf)
    if form.validate_on_submit():
        paciente.nome = form.nome.data
        paciente.data_nascimento = form.data_nascimento.data
        paciente.sexo = form.sexo.data
        paciente.telefone = form.telefone.data
        paciente.email = form.email.data
        paciente.cep = form.cep.data
        paciente.endereco = form.endereco.data
        paciente.complemento = form.complemento.data
        paciente.referencia = form.referencia.data
        paciente.updated_in = datetime.datetime.utcnow()
        db.session.commit()
        flash('Paciente editado com sucesso')
        return redirect(url_for('paciente_blueprint.pacientes', pagina=1))
    elif request.method == 'GET':
        form.cpf.data = paciente.cpf
        form.nome.data = paciente.nome
        form.data_nascimento.data = paciente.data_nascimento
        form.sexo.data = paciente.sexo
        form.telefone.data = paciente.telefone
        form.email.data = paciente.email
        form.cep.data = paciente.cep
        form.endereco.data = paciente.endereco
        form.complemento.data = paciente.complemento
        form.referencia.data = paciente.referencia
    return render_template('paciente.html', methods=['GET', 'POST'], form=form, titulo_card="Editar paciente")

app/paciente/templates/paciente.html
{% extends "base-site.html" %}

{% block title %} Pacientes {% endblock %}

{% block content %}

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css">

<script  type="text/javascript">
   $(document).ready(function(){

        $("#my-date").datepicker({
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
            dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            nextText: 'Próximo',
            prevText: 'Anterior'
        });

    });
</script>

<div class="container-fluid">
    <div class="fade-in">
        <div class="row">
            <div class="col-sm-12">
                <form role="form" method="post" id="qqq">
                <div class="card">
                    <div class="card-header"><strong>{{ titulo_card }}</strong></div>
                        <div class="card-body">
                            {{ error_form(form) }}
                            {{ form.hidden_tag() }}
                                <div class="row">
                                    <div class="form-group col-sm-2">
                                        {{ form.cpf.label() }}
                                        {{ form.cpf(class="form-control") }}
                                    </div>
                                    <div class="form-group col-sm-6">
                                      {{ form.nome.label() }}
                                      {{ form.nome(class="form-control") }}
                                    </div>
                                    <div class="form-group col-sm-2">
                                        {{ form.sexo.label() }}
                                        {{ form.sexo(class="form-control") }}
                                    </div>
                                    <div class="form-group col-sm-2">
                                        {{ form.data_nascimento.label() }}
                                        {{ form.data_nascimento(class="form-control form-date", id="my-date") }}
                                    </div>
                                </div>
                                <div class="row">
                                  <div class="form-group col-sm-6">
                                    {{ form.telefone.label() }}
                                    {{ form.telefone(class="form-control") }}
                                  </div>
                                  <div class="form-group col-sm-6">
                                    {{ form.email.label() }}
                                    {{ form.email(class="form-control") }}
                                  </div>
                                </div>
                              <div class="row">
                                <div class="form-group col-sm-5">
                                    {{ form.endereco.label() }}
                                    {{ form.endereco(class="form-control") }}
                                </div>
                                <div class="form-group col-sm-2">
                                    {{ form.complemento.label() }}
                                    {{ form.complemento(class="form-control") }}
                                </div>
                                <div class="form-group col-sm-3">
                                    {{ form.referencia.label() }}
                                    {{ form.referencia(class="form-control") }}
                                </div>
                                <div class="form-group col-sm-2">
                                    {{ form.cep.label() }}
                                    {{ form.cep(class="form-control") }}
                                </div>
                              </div>
                              <!-- /.row-->

                        </div>
                        <div class="card-footer">
                            {{ form.submit(class="btn btn-success float-right") }}
                        </div>
              </div>
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/paciente/templates/pacientes.html
{% extends "base-site.html" %}
{% block title %} Pacientes {% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="fade-in">

        <div class="card">
            <div class="card-header">
                <strong>Busca</strong>
            </div>
             <div class="card-body">
                 <form method="post">
                     {{ search_form.hidden_tag() }}
                 <div class="row">
                     <div class="col-sm-2 form-group">
                         {{ search_form.cpf.label() }}
                         {{ search_form.cpf(class="form-control") }}
                     </div>
                     <div class="col-sm-4 form-group">
                            {{ search_form.nome.label() }}
                            {{ search_form.nome(class="form-control") }}
                     </div>
                        <div class="col-sm-6 form-group align-self-end">
                          {{ search_form.submit(class="btn btn-success") }}
                        </div>
                 </div>
                 </form>
             </div>
        </div>

          <div class="card">
            <div class="card-header"><strong>Pacientes</strong>
                <div class="card-header-actions">
                  <a href="{{ url_for('paciente_blueprint.adicionar_paciente') }}" class="btn btn-primary" role="button">
                    <svg class="c-icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user-follow"></use>
                    </svg> Adicionar
                  </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-responsive-sm table-striped">
                        <thead>
                          <tr>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th>Data nascimento</th>
                            <th>Sexo</th>
                            <th>Email</th>
                            <th>Telefone</th>
                            <th>Ações</th>
                          </tr>
                        </thead>
                        <tbody>
                         <tr>
                            {% for paciente in pacientes.items %}
                            <td>{{ paciente.nome }}</td>
                            <td>{{ paciente.cpf }}</td>
                            <td>{{ paciente.data_nascimento.strftime('%d/%m/%Y') }}</td>
                             <td>{{ paciente.sexo }}</td>
                             <td>{{ paciente.email }}</td>
                             <td>{{ paciente.telefone }}</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <button class="btn btn-warning" type="button" onclick="location.href='{{ url_for('paciente_blueprint.edit_paciente', id=paciente.id) }}'">
                                        <svg class="c-icon">
                                            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
                                        </svg> Editar
                                    </button>
                                <div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                      {{ pagination(pacientes, 'paciente_blueprint.pacientes', pacientes.prev_num, pacientes.next_num) }}
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}